- menu_name: "Services"

- name: "Contact Me"
  url: "/contact/"
  title: "Contact"

- name: "My Resumé"
  url: "/assets/SienaGuerrero_Resume.pdf"
  title: "Resumé"

# - name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
