- menu_name: "Quick Links"

- name: "Support Me on Ko-fi"
  url: "https://ko-fi.com/S6S8WFPN"
  title: "Support Me on Ko-fi"

- name: "Download My Resume"
  url: "/downloads/SienaGuerrero-Resume.pdf"
  title: "Download My Resume"

- name: "Contact Me"
  url: "/contact/"
  title: "Contact"
  
- name: "About Harvey Mudd College"
  url: "https://www.hmc.edu"
  title: "HMC Website"

- name: "About HMC Computer Science"
  url: "https://www.cs.hmc.edu"
  title: "HMC Computer Science Website"

# - name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

# - name: "sitemap.xml"
#   url: "/sitemap.xml"
#   title: "Sitemap for Google Webmaster Tools"
