- menu_name: "Quick Links"

- name: "My Projects"
  url: "/my-projects/"
  title: "My Projects"

- name: "Articles"
  url: "/articles/"
  title: "Articles"

- name: "Blog"
  url: "/blog/"
  title: "Blog"

- name: "Contact Me"
  url: "/contact/"
  title: "Contact"

- name: "Download My Resume"
  url: "/downloads/SienaGuerrero-Resume.pdf"
  title: "Resume"

# - name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
