- menu_name: "Quick Links"

- name: "Contact Me"
  url: "/contact/"
  title: "Contact"

- name: "Download My Resumé"
  url: "https://drive.google.com/file/d/1woaqZqjmmLgznLeUrDItz3UWjW1oQuAQ/view?usp=sharing"
  title: "Resume"

# - name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
